name: publish
on: [push]

jobs:
  publish-image:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    container:
      image: fedora:latest

    steps:
    - name: Convert to OCI Image
      run: |
        if [[ "$GITHUB_REF_NAME" == "master" ]]; then export TAG_NAME="latest"; else export TAG_NAME="$GITHUB_REF_NAME"; fi
        echo "Building jpf91/fedora-iot:$TAG_NAME"
        sudo dnf update -y
        sudo dnf install -y rpm-ostree
        ostree init --repo=repo --mode archive
        echo '' >> repo/config
        echo '[remote "fedora-iot"]' >> repo/config
        echo 'url=https://ostree.fedoraproject.org/iot/' >> repo/config
        echo 'gpg-verify=false' >> repo/config
        echo 'contenturl=mirrorlist=https://ostree.fedoraproject.org/iot/mirrorlist' >> repo/config
        ostree pull --repo=repo --mirror fedora-iot:fedora/stable/x86_64/iot
        # ostree container encapsulate --repo=repo fedora/stable/x86_64/iot docker://ghcr.io/jpf91/fedora-iot:$TAG_NAME
        skopeo login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
        rpm-ostree compose container-encapsulate fedora/stable/x86_64/iot docker://ghcr.io/jpf91/fedora-iot:$TAG_NAME
